image: Visual Studio 2017
configuration: Release

install:
  - choco install gitversion.portable -pre -y

before_build:
  - cmd: gitversion /l console /output buildserver

build_script:
  - cmd: msbuild /t:restore;build;pack /p:Configuration=%CONFIGURATION% src\StickyWindows.sln

artifacts:
  - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: 5ppgDORFEq5HEQq6CbFnE4rwxQLSnN9xWCZXfRKANMV++mM9E1VsinyhlieKwf3a
    on:
      branch: 
        - master
        - develop